- name: "Create Directory"
  file:
    path: ~/web
    state: directory
    
- name: "Install Apache2"
  become: true
  apt:
    name: ["apache2"]
    state: latest
    update_cache: yes

- name: "Install index.js"
  template:
    src: files/index.js
    dest: ~/web/index.js
    backup: yes

- name: "Executing Node"
  shell:
    pm2 start ~/web/index.js -f
